### ISSUE TITLE
What makes it faster than the native runtime fetch api?

### ISSUE THREAD

**Issue by AllanOricil** [carboneio/rock-req#1]
I dont get it how you were able to create something that is faster than the native runtime api.

**Comment by dgrelaud** [comment]
>What makes it faster than the native runtime fetch api?

The main source: Keep-alive by default.
And rock-req is light-enough to be almost as fast as the native `http.request` of NodeJS if an http agent is used with HTTP keep-alive. 

Since Node19, NodeJS has decided to define a default keep-alive: https://github.com/nodejs/node/issues/37184
But many NodeJS projects still use Node 16 and 18.
